Calculeu els valors propis de A. Determineu els vectors propis associats a cada un dels valors propis de A. Decidiu si A és diagonalitzable o no.

In [2]:
import numpy as np

# Definir la matriz A
A = np.array([[7, 3, -9],
              [8, 5, -12],
              [6, 3, -8]])

# Calcular los valores propios y los vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

# Mostrar los valores propios y los vectores propios
print("Valores propios:")
print(eigenvalues)
print("\nVectores propios (columnas de la matriz):")
print(eigenvectors)

# Comprobar si la matriz es diagonalizable
# Una matriz es diagonalizable si tiene 3 vectores propios linealmente independientes
rank = np.linalg.matrix_rank(eigenvectors)
Diagonalizable = rank == 3

print("¿Es diagonalizable?", "Sí" if Diagonalizable else "No")

Valores propios:
[2. 1. 1.]

Vectores propios (columnas de la matriz):
[[ 0.51449576  0.59123721 -0.6625263 ]
 [ 0.68599434  0.55965564  0.72151648]
 [ 0.51449576  0.58071002 -0.20117871]]
¿Es diagonalizable? Sí
